export class UpgradeConstant {
  static UPGRADE_QUEUE = 'UPGRADE_QUEUE';

  static SOON_EXPIRED_ORDER_NOTIFY = 'SOON_EXPIRED_ORDER_NOTIFY';
  static EXPIRED_ORDER_NOTIFY = 'EXPIRED_ORDER_NOTIFY';

  static UPGRADE_TO_PHOTOGRAPHER = 'UPGRADE_TO_PHOTOGRAPHER';
}
