export class PhotoConstant {
  static PHOTO_PROCESS_QUEUE = 'PHOTO_PROCESS_QUEUE';

  static PROCESS_PHOTO_JOB_NAME = 'PROCESS_PHOTO_JOB_NAME';

  static GENERATE_WATERMARK_JOB = 'GENERATE_WATERMARK_JOB';

  static WEBSOCKET_GATEWAY = 'PHOTO_GATEWAY';

  static THUMBNAIL_WIDTH = 400;
}
