export class PhotoConstant {
  static PHOTO_PROCESS_QUEUE = 'PHOTO_PROCESS_QUEUE';
  static PHOTO_WATERMARK_QUEUE = 'PHOTO_WATERMARK_QUEUE';
  static PHOTO_VIEWCOUNT_QUEUE = 'PHOTO_VIEWCOUNT_QUEUE';

  static PROCESS_PHOTO_JOB_NAME = 'PROCESS_PHOTO_JOB_NAME';

  static UPLOAD_PHOTO_JOB_NAME = 'UPLOAD_PHOTO_JOB_NAME';

  static DELETE_PHOTO_JOB_NAME = 'DELETE_PHOTO_JOB_NAME';

  static GENERATE_WATERMARK_JOB = 'GENERATE_WATERMARK_JOB';

  static INCREASE_VIEW_COUNT_JOB = 'INCREASE_VIEW_COUNT_JOB';

  static WEBSOCKET_GATEWAY = 'PHOTO_GATEWAY';

  static THUMBNAIL_WIDTH = 720;
  static PLACEHOLDER_WIDTH = 80;

  static MIN_PHOTO_SIZE = 4000000;

  static MIN_PHOTO_WIDTH = 480;

  static TINEYE_MIN_PHOTO_WIDTH = 600;
}
